header_1: 'h1.'
header_2: 'h2.'
header_3: 'h3.'
list: '-'
bullet: '*'
numbered_list: '#'
color: '{color:<%value%>}<%text%>'
strong: '*<%text%>*'
emphasis: '_<%text%>_'
table_head: '|<%text%>|'
citation: '??<%text%>??'
deleted: '-<%text%>-'
inserted: '+<%text%>+'
superscript: '^<%text%>^'
subscript: '~<%text%>~'
monospaced: '{{<%text%>}}' 
